### ISSUE TITLE
環境構築に書かれている手順だけではcodeコマンドが使用できない

### ISSUE THREAD

**Issue by yuki2501** [kztk-m/proenb-csharp-websrc#27]
[環境構築1の動作確認](https://kztk-m.github.io/proenb-csharp/setup.html#%E5%8B%95%E4%BD%9C%E7%A2%BA%E8%AA%8D-1)の箇所で、
> その後 `code HelloWorldCS` でVSCodeを開く．

という記述があるのですが、[VSCodeの公式ドキュメント](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line)によると、macではコマンドパレットから`code`コマンドのインストール作業を行なわないと、`code`コマンドは使用できないようです。

もしかしたら読み落としている箇所があるのかもしれないのですが、確認したところ特に`code`コマンドを有効化するステップは記述されていないようだったので、今回の演習のために初めてVSCodeをインストールするといった場合を考えると、なんらかの記述があったほうがよいかもしれないとおもいました。

**Comment by kztk-m** [comment]
ありがとうございます．修正しておきます．
