### ISSUE TITLE
「環境設定2」におけるランタイムやSDKのバージョンに関する記述の追加

### ISSUE THREAD

**Issue by yuki2501** [kztk-m/proenb-csharp-websrc#8]
「環境設定2」を実施する際にGTK版をビルド・実行しようとすると、以下の画像のように、実行時、Microsoft.NETCore.Appの必要なバージョンがインストールされていないという旨のメッセージが表示され、実行されませんでした(これはエラーメッセージにあるURLから必要なバージョンのランタイムを導入するか、公式ドキュメント https://docs.microsoft.com/en-us/dotnet/core/versions/selection#framework-dependent-apps-roll-forward にあるように `<RollForward>`タグによる設定等を実施すれば解決されました)。

![](https://user-images.githubusercontent.com/23431300/162995889-d00d150b-073d-445c-8b6b-b2570daf4e84.png)

「環境設定1」でおそらく導入されるsdkのバージョン(6.0.0番台)とデフォルトのconfigファイルにあるターゲットバージョン(5.0番台)の不一致が原因に思われ、何らかの対応策が資料に記載されていると良いかなと思いました(私の環境構築手段に何かの不手際があったら申し訳ありません)。

**Comment by kztk-m** [comment]
ありがとうございます．記述を追加しました．

**Comment by kztk-m** [comment]
木曜の講義でも追加した記述に関する問題は報告されなかったので，前のコミットで問題は解決したとみなしクローズします．あらためてありがとうございました．
